# Generated by Django 4.0.2 on 2022-02-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='num_likes', to='social_network_app.postlike'),
        ),
    ]
